name: Release axoncode

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.21

      - name: Install dependencies
        run: |
          cd packages/axoncode
          bun install

      - name: Build
        run: |
          cd packages/axoncode
          bun run build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: packages/axoncode/dist/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
